[package]
name = "astinus"
version = "0.1.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]

[dependencies]
cocoa = "0.8.1"

[dependencies.gtk]
version = "0.1.2"
features = ["v3_20"]

[dependencies.rusqlite]
version = "0.10.1"
features = ["bundled"]
